spring:
  application:
    name: iam-service-test

  # Configuração para usar o Postgres do Docker (que seu log mostrou estar ativo)
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver

  jpa:
    # REMOVIDO o H2Dialect que causava o erro createClob()
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Deixa o Hibernate detectar o dialeto do Postgres sozinho
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Ativa o suporte ao Docker Compose (Postgres e Redis)
  docker:
    compose:
      lifecycle-management: start_and_stop

  # Reativando o Swagger (Estava 'false' no seu código)
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

# Configuração de Segurança
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000      # 1 dia (Access Token)
      refresh-token:
        expiration: 604800000   # 7 dias (Refresh Token)